# nginx proxy address - http://172.17.0.1:8111

name: restic
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  restic:
    image: restic/rest-server:latest
    pull_policy: always
    container_name: restic-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - restic
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8111:8000"
    environment:
      TZ: ${TZ:-America/New_York}
      PASSWORD_FILE: ${PASSWORD_FILE:-/data/.htpasswd}
      OPTIONS: ${OPTIONS:-}
      CONTAINER_NAME: restic-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    volumes:
      - ./volumes/data/restic:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://restic-app:8000'
      - 'cloudflare.hostname=restic.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.restic-app.entrypoints=http'
      - 'traefik.http.routers.restic-app-secure.tls=true'
      - 'traefik.http.routers.restic-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.restic-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.restic-app.middlewares=restic-app-https-redirect'
      - 'traefik.http.routers.restic-app-secure.entrypoints=https'
      - 'traefik.http.routers.restic-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.restic-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.restic-app-secure.service=restic-app'
      - 'traefik.http.services.restic-app.loadbalancer.server.port=8000'

networks:
  restic:
    name: restic
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
