# nginx proxy address - http://172.17.0.1:8111

name: restic
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  restic:
    image: restic/rest-server:latest
    pull_policy: always
    container_name: restic-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - restic
    ports:
      - "172.17.0.1:8111:8000"
    environment:
      TZ: ${TZ:-America/New_York}
      PASSWORD_FILE: ${PASSWORD_FILE:-/data/.htpasswd}
      OPTIONS: ${OPTIONS:-}
    volumes:
      - ./volumes/data/restic:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  restic:
    name: restic
    external: false
